export const PAYMENT_SDK = Symbol('PAYMENT_SDK');
export const CT_CART_SERVICE = Symbol('CT_CART_SERVICE');
export const CT_PAYMENT_SERVICE = Symbol('CT_PAYMENT_SERVICE');
export const CT_SESSION_AUTH_HOOK = Symbol('CT_SESSION_AUTH_HOOK');
export const CT_PAYMENT_METHOD_SERVICE = Symbol('CT_PAYMENT_METHOD_SERVICE');
export const CT_JWT_AUTH_HOOK = Symbol('CT_JWT_AUTH_HOOK');
export const CT_OAUTH2_AUTH_HOOK = Symbol('CT_OAUTH2_AUTH_HOOK');
export const CT_AUTHORITY_AUTH_HOOK = Symbol('CT_AUTHORITY_AUTH_HOOK');
